layout_spectrum: 1
color:
  saturation: 0.7625248
  lightness: 0.5486552
  brandStrength: 0.4881621
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#AFAFAF'
    - '#7A7A7A'
    - '#BDF903'
  rhythmicContrast: 0.5697111
typography_spectrum: 0.1143931
name: 'Flawless Productions '
